version: '3.0'
services:
  web:
    build:
        context: ./developer
        dockerfile: Dockerfile
    container_name: m2c_web_1
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
    container_name: m2c_db_1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    container_name: m2c_phpmyadmin_1
volumes:
  db-data: 